### ISSUE TITLE
unpaired show/dismiss calls strange behavior

### ISSUE THREAD

**Issue by dev4dev** [mutualmobile/MMProgressHUD#23]
If you call `[MMProgressHUD dismissWithSuccess:@"Complete"];` method before any show method like `[MMProgressHUD showWithStatus:@"Loading..."];` it will show checkmark image instead of loading spinner animation when you show hud next time

**Comment by larsacus** [comment]
This might be fixed in 0.3.0. Please try and reopen if the issue still persists.
