### ISSUE TITLE
it  not support arm64

### ISSUE THREAD

**Issue by xiangzi9148** [mutualmobile/MMProgressHUD#37]
i found it when i am archiving my project

The  error:

Undefined symbols for architecture x86_64:
  "_MMProgressHUDStandardDismissDelay", referenced from:
      +[MMProgressHUD(Class) dismissWithError:title:] in MMProgressHUD+Class.o
      +[MMProgressHUD(Class) dismissWithSuccess:title:] in MMProgressHUD+Class.o
ld: symbol(s) not found for architecture x86_64
Undefined symbols for architecture i386:
  "_MMProgressHUDStandardDismissDelay", referenced from:
      +[MMProgressHUD(Class) dismissWithError:title:] in MMProgressHUD+Class.o
      +[MMProgressHUD(Class) dismissWithSuccess:title:] in MMProgressHUD+Class.o
ld: symbol(s) not found for architecture i386

**Comment by larsacus** [comment]
I don't distribute this code as a pre-compiled library or framework, so you'll have to check your project or CocoaPod settings to see why this is the case. Specifically here, though, it's complaining about not being able to find the symbols for the simulator in addition to x64 (i386).
