### ISSUE TITLE
Compilation warning with Xcode 7 beta 6.

### ISSUE THREAD

**Issue by chenjsa** [mutualmobile/MMProgressHUD#38]
Compilation warning with Xcode 7 beta 6,
/Pods/MMProgressHUD/Source/MMProgressHUDViewController.m:81:1: Conflicting return type in implementation of 'supportedInterfaceOrientations': 'UIInterfaceOrientationMask' (aka 'enum UIInterfaceOrientationMask') vs 'NSUInteger' (aka 'unsigned int')

**Comment by larsacus** [comment]
This should be resolved in the latest release: 0.3.2
